// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Demo
{
	public partial class NiceButton : UIButton
	{
		protected NiceButton (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			var view = new UIView();
			view.BackgroundColor = UIColor.FromRGBA(0.6494f, 0.8155f, 1.0f, 1.0f);

			view.TranslatesAutoresizingMaskIntoConstraints = false;
			AddSubview(view);

			view.AddConstraint(NSLayoutConstraint.Create(
				view1: view,
				attribute1: NSLayoutAttribute.Height,
				relation: NSLayoutRelation.Equal,
				view2: null,
				attribute2: NSLayoutAttribute.Height,
				multiplier: 1,
				constant: 1
			));

			AddConstraint(NSLayoutConstraint.Create(
				view1: view,
				attribute1: NSLayoutAttribute.Left,
				relation: NSLayoutRelation.Equal,
				view2: this,
				attribute2: NSLayoutAttribute.Left,
				multiplier: 1,
				constant: 0
			));

			AddConstraint(NSLayoutConstraint.Create(
				view1: view,
				attribute1: NSLayoutAttribute.Right,
				relation: NSLayoutRelation.Equal,
				view2: this,
				attribute2: NSLayoutAttribute.Right,
				multiplier: 1,
				constant: 0
			));

			AddConstraint(NSLayoutConstraint.Create(
				view1: view,
				attribute1: NSLayoutAttribute.Bottom,
				relation: NSLayoutRelation.Equal,
				view2: this,
				attribute2: NSLayoutAttribute.Bottom,
				multiplier: 1,
				constant: 0
			));
		}
	}
}
